#!/usr/bin/env bash
# Build and install script for try
# Generated by repo-mole

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/prj/util/bin"

echo "=== Building try ==="
echo "Source: $SCRIPT_DIR"

# Check dependencies
echo "Checking dependencies..."
command -v ruby >/dev/null 2>&1 || { echo "ERROR: Ruby is required but not installed"; exit 1; }
echo "✓ Ruby found: $(ruby --version)"

# Verify syntax
echo "Verifying Ruby syntax..."
ruby -c "$SCRIPT_DIR/try.rb"

# Install binary
echo "Installing to $BIN_DIR..."
mkdir -p "$BIN_DIR"
cp "$SCRIPT_DIR/try.rb" "$BIN_DIR/try"
chmod +x "$BIN_DIR/try"

echo ""
echo "=== Installation Complete ==="
echo "Binary: $BIN_DIR/try"
echo ""
echo "=== SETUP STEPS REQUIRED ==="
echo ""
echo "Add shell integration to your ~/.zshrc:"
echo ""
echo '  eval "$(try init)"'
echo ""
echo "Or with a custom path for experiments:"
echo ""
echo '  eval "$(try init ~/src/tries)"'
echo ""
echo "Then restart your shell or run: source ~/.zshrc"
echo ""
echo "=== END SETUP ==="
